// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using QuickType;
//
//    var boxOfficePerDay = BoxOfficePerDay.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603
#pragma warning disable CS1591

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class BoxOfficePerDay
    {
        [JsonPropertyName("status")]
        public long Status { get; set; }

        [JsonPropertyName("des")]
        public string Des { get; set; }

        [JsonPropertyName("userstatus")]
        public long Userstatus { get; set; }

        [JsonPropertyName("version")]
        public long Version { get; set; }

        [JsonPropertyName("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonPropertyName("table2")]
        public Table2[] Table2 { get; set; }

        [JsonPropertyName("table1")]
        public Table1[] Table1 { get; set; }

        [JsonPropertyName("table0")]
        public Table0[] Table0 { get; set; }
    }

    public partial class Table0
    {
        [JsonPropertyName("TotalText")]
        public string TotalText { get; set; }

        [JsonPropertyName("UpTime")]
        public DateTimeOffset UpTime { get; set; }

        [JsonPropertyName("SumBoxOffice")]
        public double SumBoxOffice { get; set; }

        [JsonPropertyName("SumShowCount")]
        public long SumShowCount { get; set; }

        [JsonPropertyName("SumAudienceCount")]
        public long SumAudienceCount { get; set; }
    }

    public partial class Table1
    {
        [JsonPropertyName("Irank")]
        public long Irank { get; set; }

        [JsonPropertyName("MovieID")]
        public long MovieId { get; set; }

        [JsonPropertyName("EntMovieID")]
        public long EntMovieId { get; set; }

        [JsonPropertyName("MovieName")]
        public string MovieName { get; set; }

        [JsonPropertyName("EnMovieName")]
        public string EnMovieName { get; set; }

        [JsonPropertyName("BoxOffice")]
        public double BoxOffice { get; set; }

        [JsonPropertyName("ShowCount")]
        public long ShowCount { get; set; }

        [JsonPropertyName("AudienceCount")]
        public long AudienceCount { get; set; }
    }

    public partial class Table2
    {
        [JsonPropertyName("TotalCounts")]
        public long TotalCounts { get; set; }

        [JsonPropertyName("TotalPage")]
        public long TotalPage { get; set; }
    }

    public partial class BoxOfficePerDay
    {
        public static BoxOfficePerDay FromJson(string json) => JsonSerializer.Deserialize<BoxOfficePerDay>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this BoxOfficePerDay self) => JsonSerializer.Serialize(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
            get => _dateTimeStyles;
            set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
            get => _dateTimeFormat ?? string.Empty;
            set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
            get => _culture ?? CultureInfo.CurrentCulture;
            set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
            string text;


            if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
            {
                value = value.ToUniversalTime();
            }

            text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

            writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? dateText = reader.GetString();

            if (string.IsNullOrEmpty(dateText) == false)
            {
                if (!string.IsNullOrEmpty(_dateTimeFormat))
                {
                    return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                }
                else
                {
                    return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                }
            }
            else
            {
                return default(DateTimeOffset);
            }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
#pragma warning disable CS1591
